.github/workflows/build-sdk-manager.yml, .github/workflows/build-wallet-manager.yml, .github/workflows/react-widget.yml, .github/workflows/sdk-manager.yml, .github/workflows/wallet-manager.yml, .github/workflows/widget.yml
- uncomment publish pipeline
- fix names of the packages according to package.json file of workspaces packages
=> chore: name of packages and uncomment publish workflow

.github/workflows/react-widget.yml, .github/workflows/sdk-manager.yml, .github/workflows/wallet-manager.yml, .github/workflows/widget.yml, .yarnrc.yml, package.json, packages/react/package.json, packages/sdk-manager/package.json, packages/wallet-manager/package.json, packages/widget/package.json, yarn.lock
=> fix: fix sygma namespace

packages/wallet-manager/README.md
Readme for the wallet manager package
=> feat: wallet package readme

.github/workflows/wallet-manager.yml, packages/wallet-manager/package.json
=> chore: changes to version

packages/wallet-manager/README.md
=> fix: fix readme

.github/workflows/wallet-manager.yml
=> fix: remove release as prop

packages/wallet-manager/README.md, packages/wallet-manager/src/test/WalletManagerController.test.ts
- small addition to readme
- fix failing tests due to last changes
=> feat: update on readme + fix on test

packages/widget/package.json, packages/widget/src/components/amount-selector/amount-selector.ts, packages/widget/src/components/amount-selector/styles.ts, packages/widget/src/connect.ts, packages/widget/src/utils/index.ts, yarn.lock
This Pr display token balance once token is selected
Closes: #52
=> feat: adding token balance to amount component

.github/workflows/cf-deploy-widget.yml
=> chore: fix yarn version in cf deploy script

packages/widget/package.json, yarn.lock
=> fix: update sygma sdk version

packages/widget/src/components/amount-selector/amount-selector.ts, packages/widget/src/components/common/dropdown/dropdown.ts, packages/widget/src/components/network-selector/network-selector.ts
=> chore(dropdown): make options generic

.github/workflows/cd.yml
=> chore: hide chores from release notes

packages/widget/src/components/amount-selector/amount-selector.ts
=> fix: amount selector prefilled with zero

packages/widget/src/components/address-input/address-input.ts, packages/widget/tests/unit/components/address-input/address-input.test.ts
=> fix: address input not submitted on paste

packages/widget/src/components/amount-selector/amount-selector.ts, packages/widget/src/controllers/wallet-manager/token-balance.ts, packages/widget/tests/unit/components/amount-selector/amount-selector.test.ts
=> fix: re-validate on account balance change

packages/widget/src/components/transfer/fungible/fungible-token-transfer.ts
… it is complete
This PR allows user to reset state when transfer was completed
Closes: #110
=> fix: error where start new transfer isn't working

packages/widget/tests/unit/setup.ts, packages/widget/vite.config.ts
=> chore: remove lit warnings

packages/widget/src/controllers/transfers/fungible-token-transfer.ts, packages/widget/tests/unit/controllers/transfers/fungible-token-transfer.test.ts
=> fix: incorrect transfer state when disconnecting wallet after transfer completed

packages/widget/src/components/amount-selector/amount-selector.ts, packages/widget/src/components/common/dropdown/dropdown.ts, packages/widget/src/components/network-selector/network-selector.ts, packages/widget/src/components/transfer/fungible/fungible-token-transfer.ts, packages/widget/src/controllers/wallet-manager/token-balance.ts, packages/widget/tests/unit/components/amount-selector/amount-selector.test.ts
=> fix: handling when resource is unselected

packages/widget/src/components/common/buttons/connect-wallet.ts, packages/widget/src/components/common/dropdown/dropdown.ts
=> fix: typesafety when handling changed properties

packages/widget/src/components/amount-selector/amount-selector.ts, packages/widget/src/components/common/dropdown/dropdown.ts, packages/widget/src/components/network-selector/network-selector.ts, packages/widget/src/components/transfer/fungible/fungible-token-transfer.ts, packages/widget/src/controllers/transfers/fungible-token-transfer.ts, packages/widget/src/controllers/wallet-manager/token-balance.ts, packages/widget/tests/unit/components/amount-selector/amount-selector.test.ts
=> fix: switch networks and misc fixes

packages/widget/src/components/transfer/fungible/fungible-token-transfer.ts, packages/widget/src/components/transfer/fungible/transfer-button/transfer-button.ts, packages/widget/src/components/transfer/fungible/transfer-detail/index.ts, packages/widget/src/components/transfer/fungible/transfer-detail/styles.ts, packages/widget/src/components/transfer/fungible/transfer-detail/transfer-detail.ts, packages/widget/src/controllers/transfers/evm/build.ts, packages/widget/src/controllers/transfers/fungible-token-transfer.ts, packages/widget/tests/unit/components/transfer-detail/transfer-detail.test.ts
This PR adds UI in widget to display fee that will be charged on `FungibleTransfer`
https://github.com/sygmaprotocol/sygma-widget/issues/55
Closes: #55
=> feat: Display Fee

packages/widget/package.json, packages/widget/src/controllers/transfers/evm/build.ts, yarn.lock
=> fix: evm amount is now calculated as user input minus the fee

packages/widget/src/components/common/dropdown/dropdown.ts, packages/widget/src/components/network-selector/network-selector.ts, packages/widget/src/components/transfer/fungible/fungible-token-transfer.ts, packages/widget/src/components/transfer/fungible/transfer-status/styles.ts, packages/widget/src/controllers/transfers/fungible-token-transfer.ts
=> feat: reset fields after transfer is complete 

.eslintrc.json
import/no-cycle rule was  parsing dependencies causing slow eslint execution. With this change ci/lint will run a lot faster
Before:
After:
=> chore: optimize eslint

packages/widget/src/components/common/dropdown/dropdown.ts, packages/widget/src/components/common/index.ts, packages/widget/src/components/network-selector/network-selector.ts, packages/widget/src/components/transfer/fungible/fungible-token-transfer.ts, packages/widget/src/components/transfer/fungible/transfer-status/styles.ts, packages/widget/src/controllers/transfers/evm/build.ts, packages/widget/src/controllers/transfers/fungible-token-transfer.ts
- brings last changes from main into dev. I had to cherry pick those commits, because since the last merge, doing a PR from main to dev resulted in a lot of conflicts and duplicated changes.
- Main has two commits that weren't included in the last merge. One of those commits is needed for #168 
=> chore: bring changes from main to dev

.github/workflows/cd.yml
=> fix: release not working

packages/widget/src/constants.ts, packages/widget/src/controllers/wallet-manager/manager.ts
Fix adding explorer urls when adding networks into metamask
Closes: #187
=> fix: explorer urls when adding networks

packages/widget/src/components/common/dropdown/dropdown.ts, packages/widget/src/components/common/dropdown/styles.ts
Add elipsis and overflow is resource name is too long
Closes: #188
=> fix: resource name

packages/widget/src/controllers/transfers/fungible-token-transfer.ts
=> fix: source switch reset

packages/widget/src/controllers/transfers/fungible-token-transfer.ts
Fixes issue when entering invalid address format
Closes: #189
=> fix: destination address format

packages/widget/src/components/transfer/fungible/fungible-token-transfer.ts
=> fix: small fix for tangle connection
